---
title: "routing_analysis"
output: html_document
date: "2024-06-03"
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r install packages}
install.packages("Rcpp")
install.packages("fasterize")
install.packages("mapboxapi", dependencies = TRUE)
install.packages("tidyverse")
install.packages("sf")
```

```{r initialize libraries}
library(leaflet)
library(mapboxapi)
library(knitr)
library(rmdformats)
library(tidyverse)
library(sf)
library(mapboxapi)
```

```{r mapbox-auth, eval = FALSE}
api_token <- readr::read_file("mytoken.txt")

mb_access_token(api_token, install = TRUE, overwrite = TRUE)
readRenviron("~/.Renviron")
```

```{r load_data, eval=FALSE}

monuments <- read_sf("../data/anlaeg_all_25832.shp")

monuments_transformed <- st_as_sf(monuments, coords = "geometry") %>% 
  st_transform(crs = 4326)

test_rundhøj <- monuments_transformed %>% 
  filter(anlaegsbet == "Rundhøj")

test_rundhøj

```

```{r mabox-map}
library(dplyr)
library(leaflet)
library(purrr)

dk <- mb_geocode("Denmark")

data <- monuments_transformed

# Split data by group
data_split <- data %>%
  group_split(anlaegsbet)

# List all unique groups
groups <- unique(data$anlaegsbet)

# Initialize the leaflet map
mapbox_map <- leaflet() %>%
  addMapboxTiles(style_id = "outdoors-v12",
                 username = "mapbox") %>%
  setView(lng = dk[1], lat = dk[2], zoom = 6.5)

# Add markers and cluster for each group
for (layer_data in data_split) {
  group_name <- unique(layer_data$anlaegsbet)
  mapbox_map <- mapbox_map %>%
    addCircleMarkers(data = layer_data,
                     group = group_name,
                     popup = ~anlaegsbet,
                     label = ~stednavn,
                     clusterOptions = markerClusterOptions(),
                     radius = 8,
                     stroke = FALSE,
                     fillOpacity = 0.8,
                     color = "red")
}

# Add layer control and hide all groups initially
mapbox_map <- mapbox_map %>%
  addLayersControl(baseGroups = character(0), overlayGroups = groups) %>%
  addEasyButton(easyButton(
    icon = "fa-globe", title = "Zoom out",
    onClick = JS("function(btn, map){ map.setZoom(7); }"))) %>%
  addEasyButton(easyButton(
    icon = "fa-crosshairs", title = "Locate Me",
    onClick = JS("function(btn, map){map.locate({setView: true}); }")))

# Hide all groups initially
for (group in groups) {
  mapbox_map <- mapbox_map %>% hideGroup(group)
}

mapbox_map
```

