---
title: "routing_analysis"
output: html_document
date: "2024-06-03"
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r install packages eval=FALSE}
install.packages("Rcpp")
install.packages("fasterize")
install.packages("mapboxapi", dependencies = TRUE)
install.packages("tidyverse")
install.packages("sf")
install.packages("mapboxer")
```

```{r initialize libraries, message=FALSE}
library(leaflet)
library(mapboxapi)
library(knitr)
library(rmdformats)
library(tidyverse)
library(sf)
library(mapboxapi)
library(dplyr)
library(leaflet)
library(purrr)
library(htmltools)
```

```{r mapbox-auth, eval = FALSE}
#api_token <- readr::read_file("../src/mytoken.txt")
#mb_access_token(api_token, install = TRUE, overwrite = TRUE)
readRenviron("~/.Renviron")
```

```{r load_data, eval=FALSE}
monuments <- read_sf("../data/anlaeg_all_25832.shp")

monuments_transformed <- st_as_sf(monuments, coords = "geometry") %>% 
  st_transform(crs = 4326)
```

```{r plot map}
prepare_data <- function(map_data) {
  data_split <- map_data %>%
    group_split(anlaegsbet)
  groups <- unique(map_data$anlaegsbet)
  return(list(data_split = data_split, groups = groups))
}

create_map <- function(map_data) {
  dk <- mb_geocode("Denmark")
  data_prep <- prepare_data(map_data)
  data_split <- data_prep$data_split
  groups <- data_prep$groups
  
  mapbox_map <- leaflet() %>%
    addMapboxTiles(style_id = "outdoors-v12",
                   username = "mapbox") %>%
    setView(lng = dk[1], lat = dk[2], zoom = 6.5)
  
  for (layer_data in data_split) {
    group_name <- unique(layer_data$anlaegsbet)
    popup_text <- create_popup_text(layer_data)
    mapbox_map <- mapbox_map %>%
      addCircleMarkers(data = layer_data,
                       group = group_name,
                       popup = popup_text,
                       label = ~stednavn,
                       clusterOptions = markerClusterOptions(),
                       radius = 8,
                       stroke = FALSE,
                       fillOpacity = 0.8,
                       color = "red")
  }
  
  mapbox_map <- mapbox_map %>%
    addLayersControl(baseGroups = character(0), overlayGroups = groups) %>%
    addEasyButton(easyButton(
      icon = "fa-globe", title = "Zoom out",
      onClick = JS("function(btn, map){ map.setZoom(7); }"))) %>%
    addEasyButton(easyButton(
      icon = "fa-crosshairs", title = "Locate Me",
      onClick = JS("function(btn, map){map.locate({setView: true}); }")))
  
  for (group in groups) {
    mapbox_map <- mapbox_map %>% hideGroup(group)
  }
  
  return(mapbox_map)
}

create_popup_text <- function(layer_data) {
  group_name <- unique(layer_data$anlaegsbet)
  popup_text <- paste(sep = "<br/>",
                       paste0("<b><a href=''>",layer_data$stednavn,"</a></b>"),
                       layer_data$anlaegsbet,
                       paste0("Her kan man skrive, hvad ", layer_data$anlaegsbet, " er"))
  return(popup_text)
}

create_map(monuments_transformed)
```

```{r analyse monuments within buffer + distance}

# Load data
monument_attraction <- read_sf("../data/sevanlaeg_all_4326_shp/sevanlaeg_all_4326.shp")
initial_position <- mb_geocode("Aarhus", output = "sf")

# Extract coordinates
coords <- st_coordinates(initial_position)

# Create buffer
buffer <- st_buffer(initial_position, 20000)

# Check consistent projection
st_crs(buffer) == st_crs(monument_attraction)

# Clip monuments by buffer (mb_optimized_route only accepts up to 12 points)
monument_attraction_clip <- st_intersection(monument_attraction, buffer)

# Create map
map <- leaflet() %>%
  addMapboxTiles(style_id = "outdoors-v12", username = "mapbox") %>%
  setView(lng = coords[1], lat = coords[2], zoom = 11)

# Add layers to map
map <- map %>%
  addPolygons(data = buffer$geometry, fillOpacity = 0.1) %>%
  addCircleMarkers(data = monument_attraction_clip,
                   radius = 5,
                   stroke = FALSE,
                   label = ~stednavn,
                   popup = ~anlaegsbet,
                   fillOpacity = 0.8,
                   color = "red") %>%
  addCircleMarkers(data = initial_position,
                   radius = 3,
                   stroke = FALSE,
                   fillOpacity = 0.8,
                   color = "blue")

# Calculate seperate routes and plot them to map
routes_list <- lapply(monument_attraction_clip$geometry, function(x) {
  mb_directions(origin = coords, destination = st_coordinates(x), profile = "driving")
})
for (route in routes_list) {
  map <- map %>% 
    addPolylines(data = route, fillOpacity = 0.1)
}

# Optimized route along all points
coords_list <- st_coordinates(monument_attraction_clip$geometry)
coords_df <- data.frame(
  X = coords_list[, 1],
  Y = coords_list[, 2]
)
coords_sf <- st_as_sf(coords_df, coords = c("X", "Y"), crs = 4326)[1:12,]
opt_route <- mb_optimized_route(coords_sf, profile="driving")
map %>% addPolylines(data = opt_route$route)

map
```
